version: "3.9"
services:
 countries-api-service:
  image: yorbenwij/api-project-yorbenw
  ports:
    - "8000:8000"
  volumes:
    - sqlite_countries_volume:/code/sqlitedb

volumes:
  sqlite_countries_volume:
